sudo: required
python:
  - 3.6
install:
        #  - pip install --upgrade pip
        #  - pip install -r requirements/default.txt
  - pip install -U tox-travis
script:
  - make test_tox
  - make lint
services:
  - docker
