sudo: false
language: python
python:
  - "3.5"
install:
        #  - pip install --upgrade pip
        #  - pip install -r requirements/default.txt
  - pip install tox-travis
script:
  - make test_tox
  - make lint
services:
  - docker
