dist: xenial
language: python
sudo: false
python:
  - 3.6
install:
  - pip install -r requirements/default.txt
  - pip install -U tox-travis
script:
  - make lint
  - make test_adapter
services:
  - docker
