version: '3.1'
services:
  keystone:
    environment:
      KEYSTONE_HOST: keystone
      KEYSTONE_ADMIN_URL: "http://keystone:35357"
      KEYSTONE_PUBLIC_URL: "http://keystone:5000"
      KEYSTONE_INTERNAL_URL: "http://keystone:5000"
