---
version: '3.1'
services:
  adapter:
    build: .
    ports:
      - 8000:${BIND_PORT:-8000}
    links:
      - keystone:keystone
    environment:
      CONFIG_PATH: /run/secrets/adapter_config
      PERUN_LOG_LEVEL: INFO
    secrets:
      - source: adapter_config
        target: /run/secrets/adapter_config
    command: "gunicorn --worker-class gevent --log-level debug -t 300 --access-logfile '-' --workers 1 --bind ${BIND_HOST:-0.0.0.0}:${BIND_PORT:-8000} denbi.scripts.perun_propagation_service:app"
    volumes:
      - ./perun/upload:/perun/upload
  keystone:
    image: monasca/keystone
    ports:
      - 5000:5000
      - 35357:35357
secrets:
  adapter_config:
    file: ./config.py
