---
version: '3.1'
services:
  adapter:
    build: .
    ports:
      - 8000:8000
    links:
      - keystone:keystone
    environment:
      CONFIG_PATH: /run/secrets/adapter_config
      PERUN_LOG_LEVEL: INFO
    secrets:
      - adapter_config
    command: "gunicorn --log-level debug  --access-logfile '-' --workers 1 --bind ${BIND_HOST:-0.0.0.0}:${BIND_PORT:-5000} denbi.scripts.perun_propagation_service:app"
  keystone:
    image: monasca/keystone
    ports:
      - 5000:5000
      - 35357:35357
secrets:
  adapter_config:
    file: ./config.ini 
